### PR TITLE
Created Vietnamese.php

### PR DESCRIPTION
**Pull request by hostnameclub**
We created a Vietnamese translation for Afterlogic Webmail.

### CODE REVIEW

**Comment by afterlogic** [comment]
Thank you! Will make sure this is added to newest 7.5 package we're going to upload here soon.

**Comment by afterlogic** [comment]
One question. Our Google findings show that Vietnamese has no differences between singular and plural forms. However, in your translation in some places singular and plural forms are different. Is it intended or just a mistake? Thanks!

**Comment by hostnameclub** [comment]
Hi,
We tried to translate it into "native" Vietnamese, so our translators made a some overwrite word for better understand. We are professional English-Vietnamese translation team and we know it's ok. But for best translation, can you release a developer license for us?

Rgs,

**Comment by afterlogic** [comment]
Thank you for clarifications. If you need WebMail Pro license (not WebMail Lite this GitHub project is about), please contact us at http://www.afterlogic.com/helpdesk on how to get commercial license.

**Pull request merged**
